[package]
name = "indexed-db"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1.35", default-features = false, features = ["sync"] }
web-sys = { version = "0.3.66", features = ["DomException", "DomStringList", "Event", "IdbDatabase", "IdbFactory", "IdbObjectStore", "IdbObjectStoreParameters", "IdbOpenDbRequest", "IdbTransaction", "IdbTransactionMode", "IdbVersionChangeEvent", "Window"] }

[dev-dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wasm-bindgen-test = "0.3.39"
